targets:
  $default:
    builders:
      freezed:
        options:
          # Garantir geração adequada
          format: true
      json_serializable:
        options:
          # Configurações JSON
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
