targets:
  $default:
    builders:
      freezed:
        options:
          # Formatar ficheiros gerados
          format: true
      hive_generator:
        options:
          # Configurações do Hive
          auto_format: true
      json_serializable:
        options:
          # Configurações JSON
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
