name: dispatcheur_cc
description: Sistema VoIP multi-plataforma com Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # HTTP e API
  dio: ^5.4.0
  
  # Storage Local
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Navigation
  go_router: ^12.1.3
  
  # Code Generation - ESTAS DEPENDÊNCIAS ESTAVAM FALTANDO
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # UI Components
  cupertino_icons: ^1.0.6
  
  # Utilities
  logger: ^2.0.2+1
  uuid: ^4.3.3
  
  # Environment
  flutter_dotenv: ^5.1.0
  
  # Notifications
  flutter_local_notifications: ^16.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation - ESTAS DEPENDÊNCIAS ESTAVAM FALTANDO
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # Linting
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/sounds/
    - .env
